name: CICD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Build and test with Maven
      run: mvn -B package --file pom.xml

    - name: Start Spring Boot application
      run: java -jar target/your-spring-boot-app.jar
